language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 6xaBpxuu8ukYNhCvQ4EyFbdhB0V/6o66OcYy+s49Ez8rzwn0AyfY2tuk4TUgA5O9UFGecEQJvv66t2VVYGEV2XPDjlrUd52yHB6mlMnah4m4MWCnlcp4dLb1jN01S7FdROP2IOfctRAw3KojNQd35DCbFqhzm+sWgJCw9R3xhmuYrN15RLWLVKXaVRSg5MDGB0RDhC/uKI8NYQjFv5JvNb/MGQMq3RPCjYjvzzwvCIEiqtQU3y94dUWjUYbCNzuDPDhbul2ZYS2SeRaMgGgHQDkZt1mFQrzH+RbAygJCI0w3YubHme1l8dMnZssREDvDbI1djCeam8l1hQy5dG7zOB/nKyTbahDPPX6jqFsWhbVwZhKD5kM6NmBUfrMxNuKTzEZC2hYefWrOMug6NLay5/KEY9CiKnzzwQy7lk8uZOoI4l25S5HKgGq77z8L8vqDisNDZtSJBHl3UsxY5c+/08ifDBm5LOoHFt3kCrMkmW+RCDG5xBUGk0sJbtxh49dcKZ087RTB7guEcmvgAOEcB6iGi9WOuBY6VbLJJt6QDHC+jX2etk7ifKNkQRUbJ0gSOHpNpSEnyHoh7p+L3eYk7iXud/LzSkoQBpXj5iRRQSZnGf5SPLKcmPqHLW1I9biMq6kIJCndRho+5F5i9nbULtrq424rWh/4274c/lBQIcA=
  file:
    - "rehype-picture.js"
    - "rehype-picture.min.js"
  on:
    tags: true
